export const ROUTE = {
  SPLASH: 'Splash',
  AUTHENTICATED: 'Authenticated',
  UNAUTHENTICATED: 'UnAuthenticated',
  WELCOME: 'Welcome',
  LOGIN: 'Login',
  DASHBOARD: 'Dashboard',
  SETTINGS: 'Settings',
  DETAILS: 'Details',
  FORGOT_PASSWORD: 'ForgotPassword',
  RESET_PASSWORD: 'ResetPassword',
  CREATE_QUIZ: 'CreateQuiz',
  CHOOSE_CATEGORY: 'ChooseCategory',
  ADD_QUESTIONS: 'AddQuestions',
  ADD_CATEGORY: 'AddCategory',
  QUESTION_LISTING: 'QuestionsListing',
};
